#
# Travis to build sphinx docs
#
language: python

# Change to master later
branches:
 only:
  - cnh/add_sphinx

python:
 - 3.7

install:
 - pip install -U pip
 - pip install -r requirements.txt

script:
 - skip

stages:
 - build and test

jobs:
 include:
  - stage: build and test
    name: Build
    script: make html
    skip-cleanup: true
