#
# Travis to build sphinx docs
#
language: python

# Change to master later
branches:
 only:
  - cnh/add_sphinx

python:
 - 3.7

install:
 - pip install -U pip
 - pip install -r requirements.txt

script:
 - skip

stages:
 - build and test

jobs:
 include:
  - stage: build and test
    name: Build
    script: make html; pwd; touch _build/html/.nojekyll ; ls -altr _build/html
    skip-cleanup: true

deploy:
 provider: pages
 skip_cleanup: true
 keep_history: false
 verbose: true
 repo: mit-satori/mit-satori.github.io
 local_dir: _build/html
 github_token: $GH_DEPLOY_TOKEN
 target_branch: master
 on:
  all_branches: true
