name: build

on:
  push:
    branches:
    - master
        
jobs:
  buildpages:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      
      - name: install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
          
      - name: add_path
        run: |
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
          
      - name: build
        run: |
          make html
          touch _build/html/.nojekyll
          ls -altr _build/html
          
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ## GITHUB_TOKEN: ${{ secrets.WEB_PAGE_DEPLOY }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: _build/html # The folder the action should deploy.
          CLEAN: false # Automatically remove deleted files from the deploy branch
          REPOSITORY_NAME: https://github.com/mit-satori/mit-satori-test-getting-started-web
          ## ACCESS_TOKEN: ${{ secrets.WEB_PAGE_DEPLOY }}
          TARGET_FOLDER: docs  
     
        
