name: build

on:
  push:
    branches:
    - master
        
jobs:
  buildpages:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout
       uses: actions/checkout@v2.2.0
     
        
