name: build

on:
  push:
    branches:
    - master
        
jobs:
  buildpages:
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      
      - name: install
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -r requirements.txt
          
      - name: build
        run: |
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
          make html
          touch _build/html/.nojekyll
          ls -altr _build/html
     
        
